name: Build and Test Virtual Teacher App

on:
  push:
    branches:
      - main
      - SCRUM-9-Continuous-Integration
  pull_request:
    branches:
      - main

jobs:
  build-test:
    name: Build and Test Spring Boot
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'corretto'
          cache: 'maven'

      - name: Build and Test
        run: mvn -B clean package --file pom.xml

